// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilkTeaShop.Data;

#nullable disable

namespace MilkTeaShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330114532_AddBanner")]
    partial class AddBanner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MilkTeaShop.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các loại trà sữa",
                            IsActive = true,
                            Name = "Trà sữa"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Trà kết hợp trái cây",
                            IsActive = true,
                            Name = "Trà trái cây"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sinh tố xay",
                            IsActive = true,
                            Name = "Smoothie"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cà phê pha sữa",
                            IsActive = true,
                            Name = "Cà phê sữa"
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HourlySalary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HireDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlySalary = 0m,
                            Position = "Admin",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            HireDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlySalary = 50000m,
                            Position = "Manager",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            HireDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlySalary = 35000m,
                            Position = "Cashier",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.IceLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IceLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Không đá",
                            Percentage = 0
                        },
                        new
                        {
                            Id = 2,
                            Label = "Ít đá",
                            Percentage = 30
                        },
                        new
                        {
                            Id = 3,
                            Label = "Nửa đá",
                            Percentage = 50
                        },
                        new
                        {
                            Id = 4,
                            Label = "Full đá",
                            Percentage = 100
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MilkTeaShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IceLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSizeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SugarLevelId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IceLevelId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSizeId");

                    b.HasIndex("SugarLevelId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MilkTeaShop.Models.OrderItemTopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ToppingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ToppingId");

                    b.ToTable("OrderItemToppings");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 35000m,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Trà sữa truyền thống"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 45000m,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Trà sữa matcha"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 40000m,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Trà sữa oolong"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 38000m,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Trà vải lychee"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 40000m,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Trà đào cam sả"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 45000m,
                            CategoryId = 3,
                            IsAvailable = false,
                            Name = "Smoothie xoài"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 30000m,
                            CategoryId = 4,
                            IsAvailable = true,
                            Name = "Bạc sỉu"
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExtraPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExtraPrice = 0m,
                            ProductId = 1,
                            SizeName = "S"
                        },
                        new
                        {
                            Id = 2,
                            ExtraPrice = 5000m,
                            ProductId = 1,
                            SizeName = "M"
                        },
                        new
                        {
                            Id = 3,
                            ExtraPrice = 10000m,
                            ProductId = 1,
                            SizeName = "L"
                        },
                        new
                        {
                            Id = 4,
                            ExtraPrice = 0m,
                            ProductId = 2,
                            SizeName = "S"
                        },
                        new
                        {
                            Id = 5,
                            ExtraPrice = 5000m,
                            ProductId = 2,
                            SizeName = "M"
                        },
                        new
                        {
                            Id = 6,
                            ExtraPrice = 10000m,
                            ProductId = 2,
                            SizeName = "L"
                        },
                        new
                        {
                            Id = 7,
                            ExtraPrice = 0m,
                            ProductId = 3,
                            SizeName = "S"
                        },
                        new
                        {
                            Id = 8,
                            ExtraPrice = 5000m,
                            ProductId = 3,
                            SizeName = "M"
                        },
                        new
                        {
                            Id = 9,
                            ExtraPrice = 10000m,
                            ProductId = 3,
                            SizeName = "L"
                        },
                        new
                        {
                            Id = 10,
                            ExtraPrice = 0m,
                            ProductId = 4,
                            SizeName = "S"
                        },
                        new
                        {
                            Id = 11,
                            ExtraPrice = 5000m,
                            ProductId = 4,
                            SizeName = "M"
                        },
                        new
                        {
                            Id = 12,
                            ExtraPrice = 10000m,
                            ProductId = 4,
                            SizeName = "L"
                        },
                        new
                        {
                            Id = 13,
                            ExtraPrice = 0m,
                            ProductId = 5,
                            SizeName = "S"
                        },
                        new
                        {
                            Id = 14,
                            ExtraPrice = 5000m,
                            ProductId = 5,
                            SizeName = "M"
                        },
                        new
                        {
                            Id = 15,
                            ExtraPrice = 10000m,
                            ProductId = 5,
                            SizeName = "L"
                        },
                        new
                        {
                            Id = 16,
                            ExtraPrice = 0m,
                            ProductId = 6,
                            SizeName = "S"
                        },
                        new
                        {
                            Id = 17,
                            ExtraPrice = 5000m,
                            ProductId = 6,
                            SizeName = "M"
                        },
                        new
                        {
                            Id = 18,
                            ExtraPrice = 10000m,
                            ProductId = 6,
                            SizeName = "L"
                        },
                        new
                        {
                            Id = 19,
                            ExtraPrice = 0m,
                            ProductId = 7,
                            SizeName = "S"
                        },
                        new
                        {
                            Id = 20,
                            ExtraPrice = 5000m,
                            ProductId = 7,
                            SizeName = "M"
                        },
                        new
                        {
                            Id = 21,
                            ExtraPrice = 10000m,
                            ProductId = 7,
                            SizeName = "L"
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản trị viên",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quản lý cửa hàng",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nhân viên",
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Khách hàng",
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = "14:00",
                            Name = "Ca sáng",
                            StartTime = "06:00"
                        },
                        new
                        {
                            Id = 2,
                            EndTime = "22:00",
                            Name = "Ca chiều",
                            StartTime = "14:00"
                        },
                        new
                        {
                            Id = 3,
                            EndTime = "23:00",
                            Name = "Ca tối",
                            StartTime = "17:00"
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.SugarLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SugarLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Không đường",
                            Percentage = 0
                        },
                        new
                        {
                            Id = 2,
                            Label = "Ít ngọt",
                            Percentage = 30
                        },
                        new
                        {
                            Id = 3,
                            Label = "Nửa ngọt",
                            Percentage = 50
                        },
                        new
                        {
                            Id = 4,
                            Label = "Vừa ngọt",
                            Percentage = 70
                        },
                        new
                        {
                            Id = 5,
                            Label = "Bình thường",
                            Percentage = 100
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.Topping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Name = "Trân châu đen",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Name = "Trân châu trắng",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            Name = "Thạch dừa",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            Name = "Pudding trứng",
                            Price = 8000m
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            Name = "Kem phô mai",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true,
                            Name = "Thạch cà phê",
                            Price = 6000m
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@milktea.com",
                            FullName = "Admin",
                            IsActive = true,
                            PasswordHash = "5cBF7XjCujWPGx5wpuAcLWfpQFurG5LjcRslTD2MvNM=",
                            Phone = "0900000001",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager@milktea.com",
                            FullName = "Quản lý",
                            IsActive = true,
                            PasswordHash = "5cBF7XjCujWPGx5wpuAcLWfpQFurG5LjcRslTD2MvNM=",
                            Phone = "0900000002",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nhanvien@milktea.com",
                            FullName = "Nhân viên A",
                            IsActive = true,
                            PasswordHash = "5cBF7XjCujWPGx5wpuAcLWfpQFurG5LjcRslTD2MvNM=",
                            Phone = "0900000003",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("MilkTeaShop.Models.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Customer", b =>
                {
                    b.HasOne("MilkTeaShop.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("MilkTeaShop.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Employee", b =>
                {
                    b.HasOne("MilkTeaShop.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("MilkTeaShop.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Order", b =>
                {
                    b.HasOne("MilkTeaShop.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilkTeaShop.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MilkTeaShop.Models.OrderItem", b =>
                {
                    b.HasOne("MilkTeaShop.Models.IceLevel", "IceLevel")
                        .WithMany("OrderItems")
                        .HasForeignKey("IceLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTeaShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTeaShop.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTeaShop.Models.ProductSize", "ProductSize")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTeaShop.Models.SugarLevel", "SugarLevel")
                        .WithMany("OrderItems")
                        .HasForeignKey("SugarLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IceLevel");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductSize");

                    b.Navigation("SugarLevel");
                });

            modelBuilder.Entity("MilkTeaShop.Models.OrderItemTopping", b =>
                {
                    b.HasOne("MilkTeaShop.Models.OrderItem", "OrderItem")
                        .WithMany("OrderItemToppings")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTeaShop.Models.Topping", "Topping")
                        .WithMany("OrderItemToppings")
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Product", b =>
                {
                    b.HasOne("MilkTeaShop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MilkTeaShop.Models.ProductSize", b =>
                {
                    b.HasOne("MilkTeaShop.Models.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MilkTeaShop.Models.User", b =>
                {
                    b.HasOne("MilkTeaShop.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MilkTeaShop.Models.WorkSchedule", b =>
                {
                    b.HasOne("MilkTeaShop.Models.Employee", "Employee")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTeaShop.Models.Shift", "Shift")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Employee", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("MilkTeaShop.Models.IceLevel", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MilkTeaShop.Models.OrderItem", b =>
                {
                    b.Navigation("OrderItemToppings");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("MilkTeaShop.Models.ProductSize", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Shift", b =>
                {
                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("MilkTeaShop.Models.SugarLevel", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MilkTeaShop.Models.Topping", b =>
                {
                    b.Navigation("OrderItemToppings");
                });

            modelBuilder.Entity("MilkTeaShop.Models.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
